# Generated by Django 3.2.8 on 2022-01-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
